In [18]:
import pandas as pd

In [19]:
data = pd.read_csv("../datasets/transaction_history.csv")

In [20]:
mcc = pd.read_csv("../data/MCC codes.csv")

In [21]:
data = data.merge(mcc , on = 'originalMcc')

In [22]:
data.query('`Business group` == "Продаж в роздріб" ').Category.unique()

array(['Різноманітні продовольчі магазини – ринки, магазини',
       'Бакалійні магазини, супермаркети',
       'Різні товари загального призначення',
       'Магазини, що торгують зі зниженими цінами', 'Товари для дому'],
      dtype=object)

In [23]:
import time

In [24]:
current_month = current_week = int(time.strftime('%m'))

In [25]:
from datetime import datetime

In [26]:
today = datetime.today()
week_num = today.isocalendar()[1]
 
print("Week number:",week_num,"weeks")

Week number: 3 weeks

### Hight Level Report

In [27]:
custom_categories = {
    'MCC_Categories' :  [{'originalMcc' : '5812', 'custom_category': 'Харчування'},{'originalMcc' : '5499', 'custom_category': 'Харчування'},{'originalMcc' : '5411', 'custom_category': 'Харчування'}],
    'Description_Categories' : [{'description' : 'Петро С.', 'custom_category': 'Квартплата'} , {'description': '535129****2010', 'custom_category': 'Комунальний платіж'}]
}

In [28]:
mcc_categories = pd.DataFrame([category for category in custom_categories['MCC_Categories']])
mcc_categories['originalMcc'] = mcc_categories['originalMcc'].astype(int)
data_with_mcc_categories = data.merge(mcc_categories,on='originalMcc', how='left')
description_categories = pd.DataFrame([category for category in custom_categories['Description_Categories']])
data_full = data_with_mcc_categories.merge(description_categories, on='description', how='left')
data_full['custom_category_x']=  data_full['custom_category_x'].fillna(data_full['custom_category_y'])
data_full['custom_category_x']=  data_full['custom_category_x'].fillna(data_full['Business group'])
data_full  = data_full.rename(columns={'custom_category_x':'custom_category'})
del data_full['custom_category_y']

In [29]:
data_full['custom_category'].unique()

array(['Харчування', 'Фінанси', 'Різні магазини', 'Онлайн-майданчики',
       'Квартплата', 'Постачальники послуг', 'Транспортування',
       'Комунальні послуги', 'Комунальний платіж', 'Продаж в роздріб',
       'Бізнес послуги'], dtype=object)

In [30]:
data_full.query("week_number == 1").groupby( ['user_name', 'Business group', 'custom_category'] ).amount.sum().to_frame()

                                               amount
user_name Business group    custom_category
Artem     Онлайн-майданчики Онлайн-майданчики    2713
          Продаж в роздріб  Харчування           4479
          Різні магазини    Різні магазини       2082
                            Харчування            120
          Фінанси           Квартплата           7000
                            Фінанси             11177
Ira       Продаж в роздріб  Харчування             67
          Транспортування   Транспортування       217
          Фінанси           Фінанси              6541

In [31]:
Balances = pd.read_csv("../datasets/balances.csv")

### Weekly balance report

In [32]:
Weekly = data_full.query("week_number == 1").groupby( ['custom_category'] ).amount.sum().reset_index().merge(Balances.query('Period == "w"'),how='right')
Weekly = Weekly.fillna(0)

In [33]:
display(Weekly)
for category in Weekly.custom_category.unique():

    category_df = Weekly.query("custom_category == @category")

    availible = category_df['Balance'] -category_df['amount']
    availible = availible[0]
    if availible > 0 : 
        balance_report_body = f"For category {category}. You have {availible}. UAH"

    else :
        balance_report_body = f"For categpry {category}. You exceeded the weekly limit."

balance_report_body

  custom_category  amount  Balance Period
0      Харчування    4666     3000      w

'For categpry Харчування. You exceeded the weekly limit.'

### Month Balance report

In [34]:
data_full

,Unnamed: 0,id,time,description,originalMcc,amount,receiptId,type,full_date,month_number,week_number,user_name,telegram_id,Category,Business group,custom_category
0,0,QybTdwmdg1UxQYorUw,1736090319,Glovo,5499,434,E8C4-AH3E-CEA7-H0E8,outcome,2025-01-05,1,1,Artem,533452580,"Різноманітні продовольчі магазини – ринки, маг...",Продаж в роздріб,Харчування
1,1,X2L4UyGbf3mHQnmHCg,1736016367,Анатолій К.,4829,715,T0E9-MC6C-3P2P-A72C,outcome,2025-01-04,1,1,Artem,533452580,Грошові перекази,Фінанси,Фінанси
2,2,dqY1XO0j5LgB88i-DUL2,1735950685,Glovo,5499,291,NaN,outcome,2025-01-04,1,1,Artem,533452580,"Різноманітні продовольчі магазини – ринки, маг...",Продаж в роздріб,Харчування
3,3,6cexPC-Cv8T6zid9SkR7vBBmR7M,1735950685,Скасування. Glovo,5499,288,NaN,income,2025-01-04,1,1,Artem,533452580,"Різноманітні продовольчі магазини – ринки, маг...",Продаж в роздріб,Харчування
4,4,5fRWZpgp0bXROL-_vA,1735920286,Glovo,5499,521,1914-H328-TBHP-KPTP,outcome,2025-01-03,1,1,Artem,533452580,"Різноманітні продовольчі магазини – ринки, маг...",Продаж в роздріб,Харчування
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,15,thhUS4Ae3Ks3596jpQ,1736523799,Uklon,4121,123,BP2P-TTP7-PH25-0X45,outcome,2025-01-10 00:00:00,1,2,Ira,820980192,Лімузини та таксі,Транспортування,Транспортування
176,16,LMXK3qGJzR45orDwzw,1736523711,OZDOR.ROZV.KOMPLEKS,5813,2849,EP66-0H9T-EC5C-HM9E,outcome,2025-01-10 00:00:00,1,2,Ira,820980192,"Бари, коктейль-бари, дискотеки, нічні клуби і ...",Різні магазини,Різні магазини
177,17,87mf5yh7tCQLaTl57w,1736523696,Від: Артем Герасимюк,4829,3000,NaN,income,2025-01-10 00:00:00,1,2,Ira,820980192,Грошові перекази,Фінанси,Фінанси
178,18,OsoxMlBNJBa_Rtfecg,1736439073,Glovo,5499,480,4CHH-KT6B-43AH-0E49,outcome,2025-01-09 00:00:00,1,2,Ira,820980192,"Різноманітні продовольчі магазини – ринки, маг...",Продаж в роздріб,Харчування
179,19,w1fBOmFpc9X89zLQOA,1736156577,Uklon,4121,76,7677-K0M6-B740-T26E,outcome,2025-01-06 00:00:00,1,2,Ira,820980192,Лімузини та таксі,Транспортування,Транспортування

In [35]:
Monthly = data_full.query("month_number == @current_month").groupby( ['custom_category'] ).amount.sum().reset_index().merge(Balances.query('Period == "m"'),how='right')
Monthly = Monthly.fillna(0)

In [48]:
availible = category_df['Balance'] -category_df['amount']
availible = availible.reset_index()[0][0]
availible

1254

In [49]:
display(Monthly)
for category in Monthly.custom_category.unique():

    category_df = Monthly.query("custom_category == @category")

    availible = category_df['Balance'] -category_df['amount']
    availible = availible.reset_index()[0][0]
    if availible > 0 : 
        balance_report_body = f"For category {category}. You have {availible} UAH."

    else :
        balance_report_body = f"For categpry {category}. You exceeded the weekly limit."

    print(balance_report_body)

   custom_category  amount  Balance Period
0  Транспортування     746     2000      m
1       Харчування   12267    12000      m

For category Транспортування. You have 1254 UAH.
For categpry Харчування. You exceeded the weekly limit.

In [63]:
data.groupby('Business group').id.nunique()

Business group
Комунальні послуги       8
Онлайн-майданчики        3
Постачальники послуг     1
Продаж в роздріб        49
Різні магазини          12
Транспортування         18
Фінанси                 28
Name: id, dtype: int64